---
language: python

os:
  - linux
  - osx

python:
  - "3.2"
  - "3.3"
  - "3.4"

env:
  global:
    - BOOST_VERSION=1.57.0
  matrix:
    - CC=gcc-4.8 CXX=g++-4.8

before_install:
  # LINUX
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install ${CXX}; fi

install:
  # LINUX
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then $TRAVIS_BUILD_DIR/scripts/install_boost_python.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s /tmp/boost_${BOOST_VERSION//[.]/_}/boost /usr/local/include/boost; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s /tmp/boost_${BOOST_VERSION//[.]/_}/stage-python${TRAVIS_PYTHON_VERSION}/lib/* /usr/local/lib/; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ldconfig; fi

  # OSX
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost-python --with-python3; fi

  - pip install coveralls

script:
  - coverage run --source=src setup.py test

after_success:
  - coveralls

