---
language: python

os:
  - linux
  - osx

python:
  - "3.2"
#  - "3.3"
#  - "3.4"

env:
  - CC=gcc-4.8 CXX=g++-4.8

before_install:
  # LINUX
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install g++-4.8; fi

install:
  # LINUX
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install libboost-python-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo rm -f /usr/lib/libboost_python.so; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s libboost_python-py32.so /usr/lib/libboost_python.so; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo rm -f /usr/lib/libboost_python.a; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s libboost_python-py32.a /usr/lib/libboost_python.a; fi

  # OSX
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost-python --with-python3; fi

  - pip install coveralls

script:
  - coverage run --source=src setup.py test

after_success:
  - coveralls

