---
language: python

os:
  - linux
  - osx

python:
  - "3.2"
  - "3.3"
  - "3.4"

env:
  global:
    - BOOST_VERSION=1.57.0
    - LIBSTDC_VERSION=4.9
    - CLANG_VERSION=3.5

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install build-essential
  - sudo apt-get -qq install libstdc++-${LIBSTDC_VERSION}-dev
  - sudo apt-get -qq --allow-unauthenticated install clang-${CLANG_VERSION}
  - scripts/install_boost_python.sh
  - sudo ln -s /tmp/boost_${BOOST_VERSION//[.]/_}/boost /usr/local/include/boost
  - sudo ln -s /tmp/boost_${BOOST_VERSION//[.]/_}/stage-python${TRAVIS_PYTHON_VERSION}/lib/* /usr/local/lib/
  - sudo ldconfig
  - pip install coveralls

script:
  - clang++ --version
  - make clean build
  - coverage run --source=src setup.py test

after_success:
  - coveralls

